version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-ticket-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT}:8000" 
    networks:
      - event-ticket-api-network
    depends_on:
      - db
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:17
    container_name: event-ticket-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"  
    networks:
      - event-ticket-api-network

networks:
  event-ticket-api-network:
    driver: bridge